version: '2'
services:
  app:
    image: rmelick/docker-compose-up-app-container:latest
    hostname: app
    container_name: app
    ports:
     - "10080:10080"
    volumes_from:
      - appConfig:ro
    environment:
      - "constraint:node==docker-compose-up-node"
  appConfig:
    image: rmelick/docker-compose-up-data-container:latest
    environment:
      - "constraint:node==docker-compose-up-node"